name: NR Broker intention open action
description: Opens an intention
branding:
  icon: package
  color: blue

inputs:
  broker_jwt:
    description: The broker account JWT to use
    required: true
  intention_path:
    description: The path to the intention to send to the broker
    default: intention.json
  broker_url:
    default: https://broker.io.nrs.gov.bc.ca
    description: The broker url.
  quickstart:
    default: false
    description: >
      Send quickstart parameter. Valid for intentions with a single action.
      If true, the action will be started automatically.
  ttl:
    default: false
    description: >
      Time to live (ttl) of the intention. The intention must be closed (and
      all actions should finish) before the TTL expires. Set to explicitly send
      the requested TTL (in seconds). If TTL is not set (and not sent), the
      Broker's default is used.
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - id: broker-intention-open
      shell: bash
      env:
        BROKER_JWT: ${{ inputs.broker_jwt }}
        BROKER_URL: ${{ inputs.broker_url }}
        INTENTION_PATH: ${{ inputs.intention_path }}
        QUICKSTART: ${{ inputs.quickstart }}
        TTL: ${{ inputs.ttl }}
      run: intention-open.sh
